import React, { useEffect, useState } from 'react';
import { Coins, CreditCard, ArrowDownToLine, Clock, CheckCircle, AlertTriangle } from 'lucide-react';
import { Card, Button, Badge } from '../components/ui';

export default function Wallet() {
  const [data,setData]=useState<any>(null); const [buyCoins,setBuyCoins]=useState('10'); const [ref,setRef]=useState(''); const [sender,setSender]=useState(''); const [account,setAccount]=useState(''); const [withdrawCoins,setWithdrawCoins]=useState('50'); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(false);
  const load=async()=>{ const r=await fetch('/api/wallet/me',{credentials:'include'}); const j=await r.json(); if(!r.ok||!j.success) throw new Error(j.message||'Authentication required'); setData(j.data); };
  useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
  const buy=async()=>{setLoading(true);setMessage('');try{const coins=Number(buyCoins);const r=await fetch('/api/wallet/purchase',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({coins,transactionRef:ref,senderName:sender,easypaisaAccount:account})});const j=await r.json();if(!r.ok)throw new Error(j.message);setMessage(j.message);setRef('');await load();}catch(e){setMessage(e instanceof Error?e.message:'Purchase failed');}finally{setLoading(false)}};
  const withdraw=async()=>{setLoading(true);setMessage('');try{const r=await fetch('/api/wallet/withdraw',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({coins:Number(withdrawCoins),easypaisaAccount:account,accountName:sender})});const j=await r.json();if(!r.ok)throw new Error(j.message);setMessage(j.message);await load();}catch(e){setMessage(e instanceof Error?e.message:'Withdrawal failed');}finally{setLoading(false)}};
  const input='w-full rounded-lg bg-surface border border-border text-text px-3 py-2 text-sm';
  if(!data) return <div className="max-w-5xl mx-auto p-8"><Card hover={false}><p className="text-text-muted">{message||'Loading wallet...'}</p></Card></div>;
  return <div className="max-w-5xl mx-auto px-4 sm:px-6 py-8"><div className="flex items-center gap-3 mb-6"><Coins className="text-warning"/><div><h1 className="text-2xl font-bold text-white">Zyro Coins</h1><p className="text-sm text-text-muted">1 coin = Rs 4 • Minimum withdrawal = 50 coins</p></div></div>
    {message&&<div className="mb-5 p-3 rounded-lg border border-primary/30 bg-primary/10 text-sm text-text">{message}</div>}
    <div className="grid md:grid-cols-3 gap-4 mb-6"><Card hover={false}><p className="text-xs text-text-muted">Available balance</p><p className="text-3xl font-bold text-white mt-1">{data.balance} <span className="text-sm text-warning">coins</span></p></Card><Card hover={false}><p className="text-xs text-text-muted">Cash value</p><p className="text-3xl font-bold text-white mt-1">Rs {data.balance*data.rate}</p></Card><Card hover={false}><p className="text-xs text-text-muted">Rate</p><p className="text-3xl font-bold text-white mt-1">Rs {data.rate}<span className="text-sm text-text-muted"> / coin</span></p></Card></div>
    <div className="grid lg:grid-cols-2 gap-5"><Card hover={false}><div className="flex items-center gap-2 mb-4"><CreditCard size={18}/><h2 className="font-semibold text-white">Buy Coins via Easypaisa</h2></div><div className="p-3 rounded-lg bg-warning/10 border border-warning/20 mb-4 text-sm"><b>Send payment to:</b><br/>Easypaisa: <b>03413445880</b><br/>Name: <b>Abubaker Ahmed</b></div><div className="space-y-3"><input className={input} type="number" min="1" value={buyCoins} onChange={e=>setBuyCoins(e.target.value)} placeholder="Coins"/><p className="text-xs text-text-muted">You will pay Rs {Number(buyCoins||0)*data.rate}</p><input className={input} value={sender} onChange={e=>setSender(e.target.value)} placeholder="Your Easypaisa name"/><input className={input} value={account} onChange={e=>setAccount(e.target.value)} placeholder="Your Easypaisa number"/><input className={input} value={ref} onChange={e=>setRef(e.target.value)} placeholder="Easypaisa transaction ID / reference"/><Button className="w-full" onClick={buy} disabled={loading}>Submit Payment for Verification</Button></div></Card>
    <Card hover={false}><div className="flex items-center gap-2 mb-4"><ArrowDownToLine size={18}/><h2 className="font-semibold text-white">Withdraw Coins</h2></div><p className="text-sm text-text-muted mb-4">Minimum {data.minWithdrawal} coins = Rs {data.minWithdrawal*data.rate}. Coins are held while your request is pending.</p><div className="space-y-3"><input className={input} type="number" min={data.minWithdrawal} step="1" value={withdrawCoins} onChange={e=>setWithdrawCoins(e.target.value)} placeholder="Coins to withdraw"/><p className="text-xs text-text-muted">You receive Rs {Number(withdrawCoins||0)*data.rate}</p><input className={input} value={account} onChange={e=>setAccount(e.target.value)} placeholder="Receiving Easypaisa number"/><input className={input} value={sender} onChange={e=>setSender(e.target.value)} placeholder="Account holder name"/><Button className="w-full" onClick={withdraw} disabled={loading||Number(withdrawCoins)<data.minWithdrawal}>Request Withdrawal</Button></div></Card></div>
    <Card hover={false} className="mt-5"><h2 className="font-semibold text-white mb-4">Transaction History</h2>{data.transactions.length===0?<p className="text-sm text-text-muted">No transactions yet.</p>:<div className="space-y-2">{data.transactions.map((t:any)=><div key={t.id} className="flex items-center justify-between p-3 rounded-lg border border-border/30"><div className="flex items-center gap-3"><Clock size={15} className="text-text-muted"/><div><p className="text-sm text-white">{t.type} • {t.coins} coins</p><p className="text-xs text-text-muted">Rs {t.rupees} • {new Date(t.created_at).toLocaleString()}</p></div></div><Badge variant={t.status==='APPROVED'||t.status==='COMPLETED'?'success':t.status==='REJECTED'?'danger':'warning'}>{t.status}</Badge></div>)}</div>}</Card>
  </div>;
}
